### ISSUE TITLE
Generation network fails with every database selected

### ISSUE THREAD

**Issue by pidupuis** [PPiMapBuilder/PPiMapBuilder#63]
I was trying to generate a network for `P08238` with every available database selected. The following error occurs and no network is generated:

```
java.lang.NullPointerException
    at ch.picard.ppimapbuilder.networkbuilder.network.PMBCreateNetworkTask.getOrCreateNode(PMBCreateNetworkTask.java:352)
    at ch.picard.ppimapbuilder.networkbuilder.network.PMBCreateNetworkTask.createEdges(PMBCreateNetworkTask.java:302)
    at ch.picard.ppimapbuilder.networkbuilder.network.PMBCreateNetworkTask.run(PMBCreateNetworkTask.java:135)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

Didn't find the database(s) responsible(s) yet.

**Comment by pidupuis** [comment]
After investigation, it happens when `getEntryByIdentifier(interactorInOrganism, nodeAName)` returns null, so when the uniprotID get from interaction does not exist in `interactorInOrganism`.

This implies that the query retrieved interactions even if they does not come from the selected organism ?
I obtain this error with `reactome` and `spike` databases.
